version: '3.7'
networks:
  local:
    driver: bridge

services:
  mosquitto:
    image: eclipse-mosquitto
    networks:
      - local
    ports:
     - "1883:1883"
     - "8883:8883"
     - "9001:9001"
    restart: on-failure
  node-red:
    image: nodered/node-red-docker
    user: root
    volumes:
      - /data/node-red:/data
    networks:
      - local
    ports:
      - "1880:1880"
    restart: on-failure
  mongodb:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
      - /data/mongodb/configdb:/data/configdb
    networks:
      - local
    ports:
      - "27017:27017"
    restart: on-failure
